# Generated by Django 3.0.4 on 2020-03-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siecareapp', '0002_policies'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
